revert manual build and deploy gw frontend action

diff --git a/.github/workflows/manual-deploy-ten-gateway-frontend.yml b/.github/workflows/manual-deploy-ten-gateway-frontend.yml
--- a/.github/workflows/manual-deploy-ten-gateway-frontend.yml
+++ b/.github/workflows/manual-deploy-ten-gateway-frontend.yml
@@ -1,5 +1,16 @@
-name: '[M] Build and Release Ten Gateway Frontend'
-run-name: '[M] Build and Release Frontend (${{ github.event.inputs.testnet_type }})'
+# Deploys TEN Gateway Frontend on Azure for Testnet
+# Builds the TEN Gateway image, pushes the image to dockerhub and starts the TEN Gateway on Azure VM
+# This action requires the following environment variables to be set:
+# - DOCKER_BUILD_TAG_GATEWAY_FE
+# - GATEWAY_URL
+# - NETWORK_NAME
+# - TENSCAN_URL
+
+# If we are deploying to a non primary instance all those variables should be prefixed with the instance name
+# example: dexynth-GATEWAY_URL
+
+name: '[M] Deploy Ten Gateway Frontend'
+run-name: '[M] Deploy Ten Gateway Frontend ( ${{ github.event.inputs.testnet_type }} )'
 on:
   workflow_dispatch:
     inputs:
@@ -20,16 +31,17 @@ on:
         options:
           - "primary"
           - "dexynth"
-      gateway_url:
-        description: "Gateway URL (optional)"
-        required: false
-      tag:
-        description: "Tag to build and push (leave empty for latest)"
-        required: true
-        default: ''
-
 jobs:
-  build-and-release:
+  validate-inputs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Check if deployment is allowed"
+        run: |
+          if [[ "${{ github.event.inputs.instance_type }}" == "dexynth" && "${{ github.event.inputs.testnet_type }}" != "sepolia-testnet" ]]; then
+            echo "Error: Dexynth can only be deployed to sepolia-testnet."
+            exit 1
+          fi
+  build-and-deploy:
     runs-on: ubuntu-latest
     environment:
       name: ${{ github.event.inputs.testnet_type }}
@@ -39,27 +51,39 @@ jobs:
         run: |
           INSTANCE_SUFFIX=""
           INSTANCE_PREFIX=""
-          
+
           if [[ "${{ github.event.inputs.instance_type }}" != "primary" ]]; then
             INSTANCE_SUFFIX="-${{ github.event.inputs.instance_type }}"
             INSTANCE_PREFIX="${{ github.event.inputs.instance_type }}-"
           fi
 
-          if [[ -z "${{ github.event.inputs.gateway_url }}" ]]; then
-            GATEWAY_URL="${{ env.GATEWAY_URL }}"
-          else
-            GATEWAY_URL="${{ github.event.inputs.gateway_url }}"
-          fi
-
           echo "INSTANCE_SUFFIX=$INSTANCE_SUFFIX" >> $GITHUB_ENV
           echo "INSTANCE_PREFIX=$INSTANCE_PREFIX" >> $GITHUB_ENV
-          echo "GATEWAY_URL=$GATEWAY_URL" >> $GITHUB_ENV
+
 
           DNS_NAME_LABEL_GATEWAY_FE="${{ github.event.inputs.testnet_type }}-ten-gateway${INSTANCE_SUFFIX}"
           IMAGE_NAME_GATEWAY_FE="${{ github.event.inputs.testnet_type }}-fe-ten-gateway${INSTANCE_SUFFIX}"
 
           echo "DNS_NAME_LABEL_GATEWAY_FE=$DNS_NAME_LABEL_GATEWAY_FE" >> $GITHUB_ENV
           echo "IMAGE_NAME_GATEWAY_FE=$IMAGE_NAME_GATEWAY_FE" >> $GITHUB_ENV
+
+          # Set instance-specific variables
+          declare -a VAR_NAMES=(
+            "DOCKER_BUILD_TAG_GATEWAY_FE"
+            "GATEWAY_URL"
+            "NETWORK_NAME"
+            "TENSCAN_URL"
+          )
+
+          for VAR_NAME in "${VAR_NAMES[@]}"; do
+            FULL_VAR_NAME="${INSTANCE_PREFIX}${VAR_NAME}"
+            VAR_VALUE=$(jq -r --arg key "$FULL_VAR_NAME" '.[$key] // empty' <<< '${{ toJson(vars) }}')
+            if [[ -n "$VAR_VALUE" ]]; then
+              echo "${VAR_NAME}=${VAR_VALUE}" >> $GITHUB_ENV
+            else
+              echo "Warning: ${FULL_VAR_NAME} not found in vars" >&2
+            fi
+          done
 
       - name: "Print GitHub variables"
         run: |
@@ -95,18 +119,25 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: "Build and Push Docker Image"
+      - name: 'Build and Push Docker Image'
         run: |
-          VERSION="${{ github.event.inputs.tag }}"
-          if [[ -z "$VERSION" ]]; then
-            VERSION=$(git describe --tags `git rev-list --tags --max-count=1` || echo "latest")
-          fi
-          echo "VERSION=${VERSION}"
-
           DOCKER_BUILDKIT=1 docker build \
             --build-arg NEXT_PUBLIC_NETWORK_NAME=${{ env.NETWORK_NAME }} \
             --build-arg NEXT_PUBLIC_TENSCAN_URL=${{ env.TENSCAN_URL }} \
             --build-arg NEXT_PUBLIC_GATEWAY_URL=${{ env.GATEWAY_URL }} \
-            -t testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet_fe:${VERSION} \
+            -t ${{ env.DOCKER_BUILD_TAG_GATEWAY_FE }} \
             -f ./tools/walletextension/frontend/Dockerfile .
-          docker push testnetobscuronet.azurecr.io/obscuronet/obscuro_gateway_dev_testnet_fe:${VERSION}
+          docker push ${{ env.DOCKER_BUILD_TAG_GATEWAY_FE }}
+
+      - name: 'Deploy Gateway FE to Azure Container Instances'
+        uses: "azure/aci-deploy@v1"
+        with:
+          resource-group: ${{ secrets.RESOURCE_GROUP }}
+          dns-name-label: ${{ env.DNS_NAME_LABEL_GATEWAY_FE }}
+          image: ${{ env.DOCKER_BUILD_TAG_GATEWAY_FE }}
+          name: ${{ env.IMAGE_NAME_GATEWAY_FE }}
+          location: "uksouth"
+          restart-policy: "Never"
+          ports: "80"
+          cpu: 2
+          memory: 2
